## Data Types in R

R language has, no scalar 
- One diamention - Vector - One type of Data
- Two Diamention - Matrix - One type of Data
- Three Diamention - Array - One type of Data
- Single row - List - Multiple type of Data
- MALE/FEMALE, TRUE/FALSE - Factor - Categorical
- Multiple rows - Data Frame - Table


## Vectors

In [2]:
x<-c(2,3,4,5,6)
x

[1] 2 3 4 5 6

In [5]:
y<-c(x,7,x)
y

[1] 2 3 4 5 6 7 2 3 4 5 6

In [7]:
z<-1:50

#### Arithmatic Operations using vectors

In [8]:
1/x

[1] 0.5000000 0.3333333 0.2500000 0.2000000 0.1666667

In [9]:
x+y

Warning message in x + y:
"longer object length is not a multiple of shorter object length"

[1]  4  6  8 10 12  9  5  7  9 11  8

In [10]:
x-y

Warning message in x - y:
"longer object length is not a multiple of shorter object length"

[1]  0  0  0  0  0 -5  1  1  1  1 -4

In [11]:
x*y

Warning message in x * y:
"longer object length is not a multiple of shorter object length"

[1]  4  9 16 25 36 14  6 12 20 30 12

In [12]:
x/y

Warning message in x/y:
"longer object length is not a multiple of shorter object length"

[1] 1.0000000 1.0000000 1.0000000 1.0000000 1.0000000 0.2857143 1.5000000
 [8] 1.3333333 1.2500000 1.2000000 0.3333333

In [13]:
print(x)

[1] 2 3 4 5 6


In [14]:
exp(x=x)

[1]   7.389056  20.085537  54.598150 148.413159 403.428793

In [15]:
exp(x)

[1]   7.389056  20.085537  54.598150 148.413159 403.428793

In [16]:
log(x=x, base = 10)

[1] 0.3010300 0.4771213 0.6020600 0.6989700 0.7781513

In [17]:
log(x=x, base=exp(1))

[1] 0.6931472 1.0986123 1.3862944 1.6094379 1.7917595

In [18]:
log(x,base=10)

[1] 0.3010300 0.4771213 0.6020600 0.6989700 0.7781513

In [19]:
log(x=x) # base = exp(1) is default


[1] 0.6931472 1.0986123 1.3862944 1.6094379 1.7917595

In [20]:
sqrt(x)

[1] 1.414214 1.732051 2.000000 2.236068 2.449490

In [30]:
abs(-x)

[1] 2 3 4 5 6

In [31]:
sin(pi/x)

[1] 1.0000000 0.8660254 0.7071068 0.5877853 0.5000000

In [24]:
log(x=y)

[1] 0.6931472 1.0986123 1.3862944 1.6094379 1.7917595 1.9459101 0.6931472
 [8] 1.0986123 1.3862944 1.6094379 1.7917595

In [32]:
factorial(x)

[1]   2   6  24 120 720

In [37]:
round(x/y, digits = 2)

Warning message in x/y:
"longer object length is not a multiple of shorter object length"

[1] 1.00 1.00 1.00 1.00 1.00 0.29 1.50 1.33 1.25 1.20 0.33

#### Vector functions

In [25]:
length(x)

[1] 5

In [26]:
min(x)

[1] 2

In [27]:
max(x)

[1] 6

In [38]:
range(x) # returns min max

[1] 2 6

In [29]:
log(x=7.819, base= 2.38)

[1] 2.371763

In [39]:
var(x)

[1] 2.5

In [40]:
sd(x)

[1] 1.581139

In [41]:
mean(x)

[1] 4

In [42]:
median(x)

[1] 4

In [43]:
sort(x)

[1] 2 3 4 5 6

In [44]:
sort(x, decreasing = TRUE)

[1] 6 5 4 3 2

In [45]:
sum(x)

[1] 20

In [46]:
prod(x)

[1] 720

#### Missing values

In [48]:
v<-c(1,2,3,NA)

In [49]:
v

[1]  1  2  3 NA

In [50]:
is.na(v)

[1] FALSE FALSE FALSE  TRUE

In [51]:
mode(v)

[1] "numeric"

In [52]:
range(v)

[1] NA NA

In [53]:
range(v, na.rm = TRUE)

[1] 1 3

In [54]:
mean(v)

[1] NA

In [56]:
mean(v, na.rm=TRUE)

[1] 2

In [57]:
u<-c(1,2,3,"abcd")
u
mode(u)

[1] "1"    "2"    "3"    "abcd"

[1] "character"

#### Colon operator to create integer vectors

In [58]:
xx<-1:30

In [59]:
xx

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
[26] 26 27 28 29 30

In [60]:
xx[10] # returns indexed value

[1] 10

In [61]:
xx[10:15] # returns indexed values in the index range

[1] 10 11 12 13 14 15

In [62]:
xx[c(5,10,15,20)] # returns indexed value in list

[1]  5 10 15 20

In [63]:
xx[-30] # excludes the indexed number

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
[26] 26 27 28 29

In [64]:
xx[-(20:30)] # excludes the range

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19

#### Sequences

In [65]:
seq(from=5, to=10)

[1]  5  6  7  8  9 10

In [66]:
seq(5,10)

[1]  5  6  7  8  9 10

In [67]:
seq(0,10, by = 2) #spaced by 2

[1]  0  2  4  6  8 10

In [1]:
seq(0,10,length.out = 11) #Number of elements in length.out

[1]  0  1  2  3  4  5  6  7  8  9 10

In [72]:
x
y
x==y
l1<- x>3 #l1 is logical vector
l1

[1] 2 3 4 5 6

[1] 2 3 4 5 6 7 2 3 4 5 6

Warning message in x == y:
"longer object length is not a multiple of shorter object length"

[1]  TRUE  TRUE  TRUE  TRUE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE

[1] FALSE FALSE  TRUE  TRUE  TRUE

In [73]:
x+l1

[1] 2 3 5 6 7

In [74]:
v2<-1:4
v2

[1] 1 2 3 4

In [80]:
paste("Quarter",v2,sep="-") #Concatinates two vectors

[1] "Quarter-1" "Quarter-2" "Quarter-3" "Quarter-4"

In [81]:
paste(c(5,6),c(1,2,3,4),sep="-")

[1] "5-1" "6-2" "5-3" "6-4"

In [91]:
c1<-("Quarter")
c1
Quarters <- paste("Quarters", 1:4, sep="-")
Quarters

[1] "Quarter"

[1] "Quarters-1" "Quarters-2" "Quarters-3" "Quarters-4"

In [94]:
cat("Quarter",1:4,sep="-") # Concatinates two vectors
.Last.value

Quarter-1-2-3-4

NULL

In [84]:
length(Quarters)

[1] 4

In [86]:
substr(Quarters, start =9, stop=9)

[1] "-" "-" "-" "-"

In [87]:
nchar(Quarters)

[1] 10 10 10 10

In [88]:
toupper(Quarters)

[1] "QUARTERS-1" "QUARTERS-2" "QUARTERS-3" "QUARTERS-4"

In [89]:
tolower(Quarters)

[1] "quarters-1" "quarters-2" "quarters-3" "quarters-4"

In [90]:
paste(Quarters,Quarters,sep=",")

[1] "Quarters-1,Quarters-1" "Quarters-2,Quarters-2" "Quarters-3,Quarters-3"
[4] "Quarters-4,Quarters-4"

In [95]:
m2<-c("do","do not","not")
m2
grep("do",m2) #pattern matching

[1] "do"     "do not" "not"

[1] 1 2

In [96]:
m2<-c(m2,"1")
m2
grep("[a-z]",m2)
gsub("do","did",m2)

[1] "do"     "do not" "not"    "1"

[1] 1 2 3

[1] "did"     "did not" "not"     "1"

In [97]:
m2<-c(m2,"not do")

In [98]:
regexpr("do",m2)

[1]  1  1 -1 -1  5
attr(,"match.length")
[1]  2  2 -1 -1  2
attr(,"index.type")
[1] "chars"
attr(,"useBytes")
[1] TRUE

In [100]:
f<-c(5,6,7)
s<-c(4,7,6)
ifelse(f>s,f,s) # returns bigger values

[1] 5 7 7

#### Indexing Vector

In [101]:
v
v1<-v[!is.na(v)] #recreates v with non missing values
v1

[1]  1  2  3 NA

[1] 1 2 3

In [102]:
v2<-v[-4] #negative index will exclude the specific value
v2

[1] 1 2 3

## Matrix

In [103]:
M1<-matrix(data=1,nrow = 3,ncol = 3)
M1

[,1] [,2] [,3]
[1,] 1    1    1   
[2,] 1    1    1   
[3,] 1    1    1

In [104]:
dim(M1)

[1] 3 3

In [105]:
M2<-matrix(NA,nrow = 2,ncol = 2)
M2
dim(M2)

[,1] [,2]
[1,] NA   NA  
[2,] NA   NA

[1] 2 2

In [106]:
M3<-matrix(c(4,5,6,7),nrow = 2,ncol = 2)
M3

[,1] [,2]
[1,] 4    6   
[2,] 5    7

In [107]:
V1<-1:12 # vector of 12 elements
V1

[1]  1  2  3  4  5  6  7  8  9 10 11 12

In [114]:
# Create matrix from vector
M4<-matrix(V1,nrow=5) #default filled by column
M4

Warning message in matrix(V1, nrow = 5):
"data length [12] is not a sub-multiple or multiple of the number of rows [5]"

[,1] [,2] [,3]
[1,] 1     6   11  
[2,] 2     7   12  
[3,] 3     8    1  
[4,] 4     9    2  
[5,] 5    10    3

In [109]:
M5<-matrix(V1,nrow = 4,byrow = TRUE)
M5

[,1] [,2] [,3]
[1,]  1    2    3  
[2,]  4    5    6  
[3,]  7    8    9  
[4,] 10   11   12

In [110]:
V2<-1:5
V3<-V2^2
M6<-cbind(V2,V3) #Creating matrix by column bind
M6

V2 V3
[1,] 1   1
[2,] 2   4
[3,] 3   9
[4,] 4  16
[5,] 5  25

In [111]:
M6<-cbind(M6,V3*2)
M6

V2 V3   
[1,] 1   1  2
[2,] 2   4  8
[3,] 3   9 18
[4,] 4  16 32
[5,] 5  25 50

In [112]:
V2<-1:5
V3<-V2^2
M7<-rbind(V2,V3)  #Creating matrix by row bind
M7
dim(M7)


[,1] [,2] [,3] [,4] [,5]
V2 1    2    3     4    5  
V3 1    4    9    16   25

[1] 2 5

In [113]:
V2<-c(V2,6)
V1
M8<-rbind(V1,V2) #vectors of unequal length
M8

[1]  1  2  3  4  5  6  7  8  9 10 11 12

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12]
V1 1    2    3    4    5    6    7    8    9    10    11    12   
V2 1    2    3    4    5    6    1    2    3     4     5     6

 #### Manipulating row names and column names

In [121]:
M6
colnames(M6)
rownames(M6)

A B  C 
a 1  1  2
b 2  4  8
c 3  9 18
d 4 16 32
e 5 25 50

[1] "A" "B" "C"

[1] "a" "b" "c" "d" "e"

In [120]:
colnames(M6)<-c("A","B","C")
rownames(M6)<-c("a","b","c","d","e")
M6

A B  C 
a 1  1  2
b 2  4  8
c 3  9 18
d 4 16 32
e 5 25 50

#### Creating Identity MAtrix

In [123]:
M9<-diag(4)
M9

[,1] [,2] [,3] [,4]
[1,] 1    0    0    0   
[2,] 0    1    0    0   
[3,] 0    0    1    0   
[4,] 0    0    0    1

In [124]:
V2
M10<-diag(V2) # Fills vector elements in diagonal of matrix
M10

[1] 1 2 3 4 5 6

[,1] [,2] [,3] [,4] [,5] [,6]
[1,] 1    0    0    0    0    0   
[2,] 0    2    0    0    0    0   
[3,] 0    0    3    0    0    0   
[4,] 0    0    0    4    0    0   
[5,] 0    0    0    0    5    0   
[6,] 0    0    0    0    0    6

#### Indexing Matrix

In [125]:
M4

[,1] [,2] [,3]
[1,] 1     6   11  
[2,] 2     7   12  
[3,] 3     8    1  
[4,] 4     9    2  
[5,] 5    10    3

In [128]:
M4[4,2]

[1] 9

In [129]:
M4[,2]

[1]  6  7  8  9 10

In [130]:
M4[3,]

[1] 3 8 1

In [131]:
M4[,1:2] # extracts first and second colomn

[,1] [,2]
[1,] 1     6  
[2,] 2     7  
[3,] 3     8  
[4,] 4     9  
[5,] 5    10

In [132]:
M4[c(2,4),] # extracts second and fourth row

[,1] [,2] [,3]
[1,] 2    7    12  
[2,] 4    9     2

In [142]:
M4>4
M4

[,1]  [,2] [,3] 
[1,] FALSE TRUE  TRUE
[2,] FALSE TRUE  TRUE
[3,] FALSE TRUE FALSE
[4,] FALSE TRUE FALSE
[5,]  TRUE TRUE FALSE

[,1] [,2] [,3]
[1,] 1     6   11  
[2,] 2     7   12  
[3,] 3     8    1  
[4,] 4     9    2  
[5,] 5    10    3

In [138]:
M4[,2]>6


[1] FALSE  TRUE  TRUE  TRUE  TRUE

In [139]:
M4[M4[,2]>6,]


[,1] [,2] [,3]
[1,] 2     7   12  
[2,] 3     8    1  
[3,] 4     9    2  
[4,] 5    10    3

In [140]:
M4[M4[,1]>4,]


[1]  5 10  3

In [141]:
M4[TRUE,1] # TRUE gets repeated five times

[1] 1 2 3 4 5

In [144]:
M4
M4[c(FALSE,TRUE,TRUE,FALSE,FALSE),2]

[,1] [,2] [,3]
[1,] 1     6   11  
[2,] 2     7   12  
[3,] 3     8    1  
[4,] 4     9    2  
[5,] 5    10    3

[1] 7 8